### ISSUE TITLE
problems with first load of workpackages

### ISSUE THREAD

**Issue by eleaner** [opf/OpenProjectExcel#1]
Hi,

I can see the connection is established and I can see a loaded list of projects etc.
but if I try to load workpackages I am always getting the following error

The following columns are madatory: "updatestatus", "id", "lock version", "title".
I defined all the columns and it still fails

The funny part is that there is no column "title" as far as I can say, only "subject"

**Comment by bpetraus** [comment]
Hi,

this was due to some hardcoded mapping regarding language settings by user. Never tested this before. So, thank you! 

Fixed it. Everything should work fine now, in any language. I would highly appreciate, if you could test it.

Best Regards

Bernd

**Comment by eleaner** [comment]
I am sorry, it was still on my to-do list, but I lost access to the
original OpenProject install so it slipped

**Comment by tooakley** [comment]
I am still seeing this behavior.  (just re-downloaded the XLSM from the repo)

The error is *slightly* different:
The following columns are madatory: "Updatestatus", "ID", "Lock Version", "Subject".

I don't see any list of projects as eleaner described in the original post. 

![image](https://user-images.githubusercontent.com/11841539/51775336-06689080-20bb-11e9-9ec7-3981e208871b.png)

My apologies if I am missing something simple....

-todd

**Comment by bpetraus** [comment]
Hi todd,

thank you for reporting!

Can you please make a screenshot of the columns you have selected in your Excelsheet? (just the headline)

Best regards

Bernd

**Comment by bpetraus** [comment]
Hi eleaner,

thank you. Maybe theres another chance for testing it.

Best Regards

Bernd

**Comment by jbouduin** [comment]
Hello,

I even do not get that far: I get a connection error (resource not found) when trying to load workpackages.
Debugging pointed out that this happens when trying to retrieve types using SubUrlStr = "Projects/andere/types". Dokumentation of the API (http://docs.openproject.org/apiv3-doc/#types-types-by-project-get) specifies that an integer (Project ID) should be used. Do I miss something here, or is this wrongly coded?


Kind regards
Johan

**Comment by bpetraus** [comment]
Hi Johan,

its not the integer (Project ID) to be used. Try Identifier instead. (You can find this in Project Settings or in every URL within a project, e.g.: plugins is the identifier in this project: https://community.openproject.com/projects/plugins?jump=homescreen)

Best Regards

Bernd

**Comment by tooakley** [comment]
Bernd, 
I didn't see any instructions for selecting columns. I get the error when first trying to connect to the OpenProject instance. After the error, there is no data in the XLSX, even though it looks like it's successfully connected to the server.
![image](https://user-images.githubusercontent.com/11841539/51918321-f09ee800-23a6-11e9-88fa-664272f4358f.png)

**Comment by byneoseb** [comment]
> 
> 
> Bernd,
> I didn't see any instructions for selecting columns. I get the error when first trying to connect to the OpenProject instance. After the error, there is no data in the XLSX, even though it looks like it's successfully connected to the server.
> ![image](https://user-images.githubusercontent.com/11841539/51918321-f09ee800-23a6-11e9-88fa-664272f4358f.png)

Hi tooakley

I have Excel 2019 and I was a same issue like you. You have to fill in yourself with columns that missing.
After that it works !

![excel](https://user-images.githubusercontent.com/10479138/51922445-56ac5f00-23e9-11e9-8213-3cabe4708c4e.PNG)

**Comment by tooakley** [comment]
That was it! I see it now. Thanks for you patience w/ a newbie!

**Comment by bpetraus** [comment]
Hi guys,

thank you, byneoseb! Thats how its meant to be.

I'll close this issue, because it seems to work, no matter what lnguage is selected. (initial problem)

Dont hesitate to open a new issue, when you discover a new problem.

Btw.: It might be useful to make an intrudoction video. I will do so in the next days.

Bernd
